#create_clock -period 1.250 -name clk [get_ports clk]
#时钟直接连接到了clk_wiz，自动写了这个时钟的约束，这里可以不写，只要在clk_wiz设置对应频率
set_property PACKAGE_PIN P15 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

#set_property STEPS.SYNTH_DESIGN.ARGS.directive Performance_Explore [get_runs synth_1]
#set_property STEPS.SYNTH_DESIGN.ARGS.global_retiming true [get_runs synth_1]
#set_property STEPS.OPT_DESIGN.ARGS.retiming true [get_runs impl_1]
#set_property STEPS.PHYS_OPT_DESIGN.ARGS.directive AggressiveExplore [get_runs impl_1]
#set_param synth.xor_carry_chain true

set_property PACKAGE_PIN A11 [get_ports {key_in[7]}]
set_property PACKAGE_PIN A12 [get_ports {key_in[6]}]
set_property PACKAGE_PIN A13 [get_ports {key_in[5]}]
set_property PACKAGE_PIN A14 [get_ports {key_in[4]}]
set_property PACKAGE_PIN A16 [get_ports {key_in[3]}]
set_property PACKAGE_PIN A17 [get_ports {key_in[2]}]
set_property PACKAGE_PIN A19 [get_ports {key_in[0]}]
set_property PACKAGE_PIN A18 [get_ports {key_in[1]}]
set_property PACKAGE_PIN A20 [get_ports {result[7]}]
set_property PACKAGE_PIN A21 [get_ports {result[6]}]
set_property PACKAGE_PIN AA1 [get_ports {result[5]}]
set_property PACKAGE_PIN AA2 [get_ports {result[4]}]
set_property PACKAGE_PIN AA3 [get_ports {result[3]}]
set_property PACKAGE_PIN AA6 [get_ports {result[2]}]
set_property PACKAGE_PIN AA7 [get_ports {result[1]}]
set_property PACKAGE_PIN AA8 [get_ports {result[0]}]
set_property PACKAGE_PIN AA9 [get_ports {text_in[7]}]
set_property PACKAGE_PIN AA10 [get_ports {text_in[6]}]
set_property PACKAGE_PIN AA20 [get_ports {text_in[5]}]
set_property PACKAGE_PIN AA21 [get_ports {text_in[4]}]
set_property PACKAGE_PIN AB2 [get_ports {text_in[3]}]
set_property PACKAGE_PIN AB3 [get_ports {text_in[2]}]
set_property PACKAGE_PIN AB4 [get_ports {text_in[1]}]
set_property PACKAGE_PIN AB6 [get_ports {text_in[0]}]
set_property PACKAGE_PIN AB9 [get_ports key_valid]
set_property PACKAGE_PIN AB10 [get_ports result_valid]
set_property PACKAGE_PIN AB20 [get_ports rst_n]
set_property PACKAGE_PIN B14 [get_ports text_valid]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {result[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {text_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {text_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {text_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {text_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {text_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {text_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {text_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {text_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports key_valid]
set_property IOSTANDARD LVCMOS33 [get_ports result_valid]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports text_valid]

set_property PACKAGE_PIN E19 [get_ports decrypt]
set_property IOSTANDARD LVCMOS33 [get_ports decrypt]


